language: java
jdk:
    - openjdk7
    - oraclejdk7
    - oraclejdk8
script: mvn verify

after_success:
    - mvn clean cobertura:cobertura org.eluder.coveralls:coveralls-maven-plugin:report -DrepoToken=${coveralls_token}
