// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: core/src/test/protobuf/simple.proto

package cereal.impl.objects.protobuf;

@SuppressWarnings("unused")
public final class SimpleOuter {
  private SimpleOuter() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface SimpleOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cereal.protobuf.Simple)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>optional double dub = 1;</code>
     */
    boolean hasDub();
    /**
     * <code>optional double dub = 1;</code>
     */
    double getDub();

    /**
     * <code>optional float flt = 2;</code>
     */
    boolean hasFlt();
    /**
     * <code>optional float flt = 2;</code>
     */
    float getFlt();

    /**
     * <code>optional int32 int = 3;</code>
     */
    boolean hasInt();
    /**
     * <code>optional int32 int = 3;</code>
     */
    int getInt();

    /**
     * <code>optional int64 long = 4;</code>
     */
    boolean hasLong();
    /**
     * <code>optional int64 long = 4;</code>
     */
    long getLong();

    /**
     * <code>optional bool boolean = 5;</code>
     */
    boolean hasBoolean();
    /**
     * <code>optional bool boolean = 5;</code>
     */
    boolean getBoolean();

    /**
     * <code>optional string str = 6;</code>
     */
    boolean hasStr();
    /**
     * <code>optional string str = 6;</code>
     */
    java.lang.String getStr();
    /**
     * <code>optional string str = 6;</code>
     */
    com.google.protobuf.ByteString
        getStrBytes();

    /**
     * <code>optional bytes byte_str = 7;</code>
     */
    boolean hasByteStr();
    /**
     * <code>optional bytes byte_str = 7;</code>
     */
    com.google.protobuf.ByteString getByteStr();
  }
  /**
   * Protobuf type {@code cereal.protobuf.Simple}
   */
  public static final class Simple extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:cereal.protobuf.Simple)
      SimpleOrBuilder {
    // Use Simple.newBuilder() to construct.
    private Simple(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Simple(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Simple defaultInstance;
    public static Simple getDefaultInstance() {
      return defaultInstance;
    }

    public Simple getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Simple(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 9: {
              bitField0_ |= 0x00000001;
              dub_ = input.readDouble();
              break;
            }
            case 21: {
              bitField0_ |= 0x00000002;
              flt_ = input.readFloat();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              int_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              long_ = input.readInt64();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              boolean_ = input.readBool();
              break;
            }
            case 50: {
              com.google.protobuf.ByteString bs = input.readBytes();
              bitField0_ |= 0x00000020;
              str_ = bs;
              break;
            }
            case 58: {
              bitField0_ |= 0x00000040;
              byteStr_ = input.readBytes();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cereal.impl.objects.protobuf.SimpleOuter.internal_static_cereal_protobuf_Simple_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cereal.impl.objects.protobuf.SimpleOuter.internal_static_cereal_protobuf_Simple_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cereal.impl.objects.protobuf.SimpleOuter.Simple.class, cereal.impl.objects.protobuf.SimpleOuter.Simple.Builder.class);
    }

    public static com.google.protobuf.Parser<Simple> PARSER =
        new com.google.protobuf.AbstractParser<Simple>() {
      public Simple parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Simple(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Simple> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int DUB_FIELD_NUMBER = 1;
    private double dub_;
    /**
     * <code>optional double dub = 1;</code>
     */
    public boolean hasDub() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional double dub = 1;</code>
     */
    public double getDub() {
      return dub_;
    }

    public static final int FLT_FIELD_NUMBER = 2;
    private float flt_;
    /**
     * <code>optional float flt = 2;</code>
     */
    public boolean hasFlt() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional float flt = 2;</code>
     */
    public float getFlt() {
      return flt_;
    }

    public static final int INT_FIELD_NUMBER = 3;
    private int int_;
    /**
     * <code>optional int32 int = 3;</code>
     */
    public boolean hasInt() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional int32 int = 3;</code>
     */
    public int getInt() {
      return int_;
    }

    public static final int LONG_FIELD_NUMBER = 4;
    private long long_;
    /**
     * <code>optional int64 long = 4;</code>
     */
    public boolean hasLong() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional int64 long = 4;</code>
     */
    public long getLong() {
      return long_;
    }

    public static final int BOOLEAN_FIELD_NUMBER = 5;
    private boolean boolean_;
    /**
     * <code>optional bool boolean = 5;</code>
     */
    public boolean hasBoolean() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool boolean = 5;</code>
     */
    public boolean getBoolean() {
      return boolean_;
    }

    public static final int STR_FIELD_NUMBER = 6;
    private java.lang.Object str_;
    /**
     * <code>optional string str = 6;</code>
     */
    public boolean hasStr() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional string str = 6;</code>
     */
    public java.lang.String getStr() {
      java.lang.Object ref = str_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          str_ = s;
        }
        return s;
      }
    }
    /**
     * <code>optional string str = 6;</code>
     */
    public com.google.protobuf.ByteString
        getStrBytes() {
      java.lang.Object ref = str_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        str_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BYTE_STR_FIELD_NUMBER = 7;
    private com.google.protobuf.ByteString byteStr_;
    /**
     * <code>optional bytes byte_str = 7;</code>
     */
    public boolean hasByteStr() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bytes byte_str = 7;</code>
     */
    public com.google.protobuf.ByteString getByteStr() {
      return byteStr_;
    }

    private void initFields() {
      dub_ = 0D;
      flt_ = 0F;
      int_ = 0;
      long_ = 0L;
      boolean_ = false;
      str_ = "";
      byteStr_ = com.google.protobuf.ByteString.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeDouble(1, dub_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeFloat(2, flt_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, int_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt64(4, long_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(5, boolean_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeBytes(6, getStrBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(7, byteStr_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, dub_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, flt_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, int_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(4, long_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(5, boolean_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(6, getStrBytes());
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(7, byteStr_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cereal.impl.objects.protobuf.SimpleOuter.Simple parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cereal.impl.objects.protobuf.SimpleOuter.Simple parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cereal.impl.objects.protobuf.SimpleOuter.Simple parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cereal.impl.objects.protobuf.SimpleOuter.Simple parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cereal.impl.objects.protobuf.SimpleOuter.Simple parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cereal.impl.objects.protobuf.SimpleOuter.Simple parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cereal.impl.objects.protobuf.SimpleOuter.Simple parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cereal.impl.objects.protobuf.SimpleOuter.Simple parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cereal.impl.objects.protobuf.SimpleOuter.Simple parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cereal.impl.objects.protobuf.SimpleOuter.Simple parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cereal.impl.objects.protobuf.SimpleOuter.Simple prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cereal.protobuf.Simple}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cereal.protobuf.Simple)
        cereal.impl.objects.protobuf.SimpleOuter.SimpleOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cereal.impl.objects.protobuf.SimpleOuter.internal_static_cereal_protobuf_Simple_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cereal.impl.objects.protobuf.SimpleOuter.internal_static_cereal_protobuf_Simple_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cereal.impl.objects.protobuf.SimpleOuter.Simple.class, cereal.impl.objects.protobuf.SimpleOuter.Simple.Builder.class);
      }

      // Construct using cereal.objects.protobuf.SimpleOuter.Simple.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        dub_ = 0D;
        bitField0_ = (bitField0_ & ~0x00000001);
        flt_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000002);
        int_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        long_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000008);
        boolean_ = false;
        bitField0_ = (bitField0_ & ~0x00000010);
        str_ = "";
        bitField0_ = (bitField0_ & ~0x00000020);
        byteStr_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cereal.impl.objects.protobuf.SimpleOuter.internal_static_cereal_protobuf_Simple_descriptor;
      }

      public cereal.impl.objects.protobuf.SimpleOuter.Simple getDefaultInstanceForType() {
        return cereal.impl.objects.protobuf.SimpleOuter.Simple.getDefaultInstance();
      }

      public cereal.impl.objects.protobuf.SimpleOuter.Simple build() {
        cereal.impl.objects.protobuf.SimpleOuter.Simple result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cereal.impl.objects.protobuf.SimpleOuter.Simple buildPartial() {
        cereal.impl.objects.protobuf.SimpleOuter.Simple result = new cereal.impl.objects.protobuf.SimpleOuter.Simple(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.dub_ = dub_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.flt_ = flt_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.int_ = int_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.long_ = long_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.boolean_ = boolean_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.str_ = str_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.byteStr_ = byteStr_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cereal.impl.objects.protobuf.SimpleOuter.Simple) {
          return mergeFrom((cereal.impl.objects.protobuf.SimpleOuter.Simple)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cereal.impl.objects.protobuf.SimpleOuter.Simple other) {
        if (other == cereal.impl.objects.protobuf.SimpleOuter.Simple.getDefaultInstance()) return this;
        if (other.hasDub()) {
          setDub(other.getDub());
        }
        if (other.hasFlt()) {
          setFlt(other.getFlt());
        }
        if (other.hasInt()) {
          setInt(other.getInt());
        }
        if (other.hasLong()) {
          setLong(other.getLong());
        }
        if (other.hasBoolean()) {
          setBoolean(other.getBoolean());
        }
        if (other.hasStr()) {
          bitField0_ |= 0x00000020;
          str_ = other.str_;
          onChanged();
        }
        if (other.hasByteStr()) {
          setByteStr(other.getByteStr());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cereal.impl.objects.protobuf.SimpleOuter.Simple parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cereal.impl.objects.protobuf.SimpleOuter.Simple) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private double dub_ ;
      /**
       * <code>optional double dub = 1;</code>
       */
      public boolean hasDub() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional double dub = 1;</code>
       */
      public double getDub() {
        return dub_;
      }
      /**
       * <code>optional double dub = 1;</code>
       */
      public Builder setDub(double value) {
        bitField0_ |= 0x00000001;
        dub_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional double dub = 1;</code>
       */
      public Builder clearDub() {
        bitField0_ = (bitField0_ & ~0x00000001);
        dub_ = 0D;
        onChanged();
        return this;
      }

      private float flt_ ;
      /**
       * <code>optional float flt = 2;</code>
       */
      public boolean hasFlt() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional float flt = 2;</code>
       */
      public float getFlt() {
        return flt_;
      }
      /**
       * <code>optional float flt = 2;</code>
       */
      public Builder setFlt(float value) {
        bitField0_ |= 0x00000002;
        flt_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float flt = 2;</code>
       */
      public Builder clearFlt() {
        bitField0_ = (bitField0_ & ~0x00000002);
        flt_ = 0F;
        onChanged();
        return this;
      }

      private int int_ ;
      /**
       * <code>optional int32 int = 3;</code>
       */
      public boolean hasInt() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional int32 int = 3;</code>
       */
      public int getInt() {
        return int_;
      }
      /**
       * <code>optional int32 int = 3;</code>
       */
      public Builder setInt(int value) {
        bitField0_ |= 0x00000004;
        int_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int32 int = 3;</code>
       */
      public Builder clearInt() {
        bitField0_ = (bitField0_ & ~0x00000004);
        int_ = 0;
        onChanged();
        return this;
      }

      private long long_ ;
      /**
       * <code>optional int64 long = 4;</code>
       */
      public boolean hasLong() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional int64 long = 4;</code>
       */
      public long getLong() {
        return long_;
      }
      /**
       * <code>optional int64 long = 4;</code>
       */
      public Builder setLong(long value) {
        bitField0_ |= 0x00000008;
        long_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional int64 long = 4;</code>
       */
      public Builder clearLong() {
        bitField0_ = (bitField0_ & ~0x00000008);
        long_ = 0L;
        onChanged();
        return this;
      }

      private boolean boolean_ ;
      /**
       * <code>optional bool boolean = 5;</code>
       */
      public boolean hasBoolean() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional bool boolean = 5;</code>
       */
      public boolean getBoolean() {
        return boolean_;
      }
      /**
       * <code>optional bool boolean = 5;</code>
       */
      public Builder setBoolean(boolean value) {
        bitField0_ |= 0x00000010;
        boolean_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool boolean = 5;</code>
       */
      public Builder clearBoolean() {
        bitField0_ = (bitField0_ & ~0x00000010);
        boolean_ = false;
        onChanged();
        return this;
      }

      private java.lang.Object str_ = "";
      /**
       * <code>optional string str = 6;</code>
       */
      public boolean hasStr() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>optional string str = 6;</code>
       */
      public java.lang.String getStr() {
        java.lang.Object ref = str_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            str_ = s;
          }
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>optional string str = 6;</code>
       */
      public com.google.protobuf.ByteString
          getStrBytes() {
        java.lang.Object ref = str_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          str_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>optional string str = 6;</code>
       */
      public Builder setStr(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        str_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional string str = 6;</code>
       */
      public Builder clearStr() {
        bitField0_ = (bitField0_ & ~0x00000020);
        str_ = getDefaultInstance().getStr();
        onChanged();
        return this;
      }
      /**
       * <code>optional string str = 6;</code>
       */
      public Builder setStrBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000020;
        str_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.ByteString byteStr_ = com.google.protobuf.ByteString.EMPTY;
      /**
       * <code>optional bytes byte_str = 7;</code>
       */
      public boolean hasByteStr() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bytes byte_str = 7;</code>
       */
      public com.google.protobuf.ByteString getByteStr() {
        return byteStr_;
      }
      /**
       * <code>optional bytes byte_str = 7;</code>
       */
      public Builder setByteStr(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        byteStr_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bytes byte_str = 7;</code>
       */
      public Builder clearByteStr() {
        bitField0_ = (bitField0_ & ~0x00000040);
        byteStr_ = getDefaultInstance().getByteStr();
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:cereal.protobuf.Simple)
    }

    static {
      defaultInstance = new Simple(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:cereal.protobuf.Simple)
  }

  public interface ComplexOrBuilder extends
      // @@protoc_insertion_point(interface_extends:cereal.protobuf.Complex)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>repeated string str_list = 1;</code>
     */
    com.google.protobuf.ProtocolStringList
        getStrListList();
    /**
     * <code>repeated string str_list = 1;</code>
     */
    int getStrListCount();
    /**
     * <code>repeated string str_list = 1;</code>
     */
    java.lang.String getStrList(int index);
    /**
     * <code>repeated string str_list = 1;</code>
     */
    com.google.protobuf.ByteString
        getStrListBytes(int index);
  }
  /**
   * Protobuf type {@code cereal.protobuf.Complex}
   */
  public static final class Complex extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:cereal.protobuf.Complex)
      ComplexOrBuilder {
    // Use Complex.newBuilder() to construct.
    private Complex(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Complex(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Complex defaultInstance;
    public static Complex getDefaultInstance() {
      return defaultInstance;
    }

    public Complex getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Complex(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              com.google.protobuf.ByteString bs = input.readBytes();
              if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
                strList_ = new com.google.protobuf.LazyStringArrayList();
                mutable_bitField0_ |= 0x00000001;
              }
              strList_.add(bs);
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
          strList_ = strList_.getUnmodifiableView();
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return cereal.impl.objects.protobuf.SimpleOuter.internal_static_cereal_protobuf_Complex_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return cereal.impl.objects.protobuf.SimpleOuter.internal_static_cereal_protobuf_Complex_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              cereal.impl.objects.protobuf.SimpleOuter.Complex.class, cereal.impl.objects.protobuf.SimpleOuter.Complex.Builder.class);
    }

    public static com.google.protobuf.Parser<Complex> PARSER =
        new com.google.protobuf.AbstractParser<Complex>() {
      public Complex parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Complex(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Complex> getParserForType() {
      return PARSER;
    }

    public static final int STR_LIST_FIELD_NUMBER = 1;
    private com.google.protobuf.LazyStringList strList_;
    /**
     * <code>repeated string str_list = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getStrListList() {
      return strList_;
    }
    /**
     * <code>repeated string str_list = 1;</code>
     */
    public int getStrListCount() {
      return strList_.size();
    }
    /**
     * <code>repeated string str_list = 1;</code>
     */
    public java.lang.String getStrList(int index) {
      return strList_.get(index);
    }
    /**
     * <code>repeated string str_list = 1;</code>
     */
    public com.google.protobuf.ByteString
        getStrListBytes(int index) {
      return strList_.getByteString(index);
    }

    private void initFields() {
      strList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (int i = 0; i < strList_.size(); i++) {
        output.writeBytes(1, strList_.getByteString(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      {
        int dataSize = 0;
        for (int i = 0; i < strList_.size(); i++) {
          dataSize += com.google.protobuf.CodedOutputStream
            .computeBytesSizeNoTag(strList_.getByteString(i));
        }
        size += dataSize;
        size += 1 * getStrListList().size();
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static cereal.impl.objects.protobuf.SimpleOuter.Complex parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cereal.impl.objects.protobuf.SimpleOuter.Complex parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cereal.impl.objects.protobuf.SimpleOuter.Complex parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static cereal.impl.objects.protobuf.SimpleOuter.Complex parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static cereal.impl.objects.protobuf.SimpleOuter.Complex parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cereal.impl.objects.protobuf.SimpleOuter.Complex parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static cereal.impl.objects.protobuf.SimpleOuter.Complex parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static cereal.impl.objects.protobuf.SimpleOuter.Complex parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static cereal.impl.objects.protobuf.SimpleOuter.Complex parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static cereal.impl.objects.protobuf.SimpleOuter.Complex parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(cereal.impl.objects.protobuf.SimpleOuter.Complex prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code cereal.protobuf.Complex}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:cereal.protobuf.Complex)
        cereal.impl.objects.protobuf.SimpleOuter.ComplexOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return cereal.impl.objects.protobuf.SimpleOuter.internal_static_cereal_protobuf_Complex_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return cereal.impl.objects.protobuf.SimpleOuter.internal_static_cereal_protobuf_Complex_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                cereal.impl.objects.protobuf.SimpleOuter.Complex.class, cereal.impl.objects.protobuf.SimpleOuter.Complex.Builder.class);
      }

      // Construct using cereal.objects.protobuf.SimpleOuter.Complex.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        strList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return cereal.impl.objects.protobuf.SimpleOuter.internal_static_cereal_protobuf_Complex_descriptor;
      }

      public cereal.impl.objects.protobuf.SimpleOuter.Complex getDefaultInstanceForType() {
        return cereal.impl.objects.protobuf.SimpleOuter.Complex.getDefaultInstance();
      }

      public cereal.impl.objects.protobuf.SimpleOuter.Complex build() {
        cereal.impl.objects.protobuf.SimpleOuter.Complex result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public cereal.impl.objects.protobuf.SimpleOuter.Complex buildPartial() {
        cereal.impl.objects.protobuf.SimpleOuter.Complex result = new cereal.impl.objects.protobuf.SimpleOuter.Complex(this);
        int from_bitField0_ = bitField0_;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          strList_ = strList_.getUnmodifiableView();
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.strList_ = strList_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof cereal.impl.objects.protobuf.SimpleOuter.Complex) {
          return mergeFrom((cereal.impl.objects.protobuf.SimpleOuter.Complex)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(cereal.impl.objects.protobuf.SimpleOuter.Complex other) {
        if (other == cereal.impl.objects.protobuf.SimpleOuter.Complex.getDefaultInstance()) return this;
        if (!other.strList_.isEmpty()) {
          if (strList_.isEmpty()) {
            strList_ = other.strList_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureStrListIsMutable();
            strList_.addAll(other.strList_);
          }
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        cereal.impl.objects.protobuf.SimpleOuter.Complex parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (cereal.impl.objects.protobuf.SimpleOuter.Complex) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private com.google.protobuf.LazyStringList strList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      private void ensureStrListIsMutable() {
        if (!((bitField0_ & 0x00000001) == 0x00000001)) {
          strList_ = new com.google.protobuf.LazyStringArrayList(strList_);
          bitField0_ |= 0x00000001;
         }
      }
      /**
       * <code>repeated string str_list = 1;</code>
       */
      public com.google.protobuf.ProtocolStringList
          getStrListList() {
        return strList_.getUnmodifiableView();
      }
      /**
       * <code>repeated string str_list = 1;</code>
       */
      public int getStrListCount() {
        return strList_.size();
      }
      /**
       * <code>repeated string str_list = 1;</code>
       */
      public java.lang.String getStrList(int index) {
        return strList_.get(index);
      }
      /**
       * <code>repeated string str_list = 1;</code>
       */
      public com.google.protobuf.ByteString
          getStrListBytes(int index) {
        return strList_.getByteString(index);
      }
      /**
       * <code>repeated string str_list = 1;</code>
       */
      public Builder setStrList(
          int index, java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStrListIsMutable();
        strList_.set(index, value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string str_list = 1;</code>
       */
      public Builder addStrList(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStrListIsMutable();
        strList_.add(value);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string str_list = 1;</code>
       */
      public Builder addAllStrList(
          java.lang.Iterable<java.lang.String> values) {
        ensureStrListIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, strList_);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string str_list = 1;</code>
       */
      public Builder clearStrList() {
        strList_ = com.google.protobuf.LazyStringArrayList.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
        return this;
      }
      /**
       * <code>repeated string str_list = 1;</code>
       */
      public Builder addStrListBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  ensureStrListIsMutable();
        strList_.add(value);
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:cereal.protobuf.Complex)
    }

    static {
      defaultInstance = new Complex(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:cereal.protobuf.Complex)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cereal_protobuf_Simple_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cereal_protobuf_Simple_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_cereal_protobuf_Complex_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_cereal_protobuf_Complex_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n#core/src/test/protobuf/simple.proto\022\017c" +
      "ereal.protobuf\"m\n\006Simple\022\013\n\003dub\030\001 \001(\001\022\013\n" +
      "\003flt\030\002 \001(\002\022\013\n\003int\030\003 \001(\005\022\014\n\004long\030\004 \001(\003\022\017\n" +
      "\007boolean\030\005 \001(\010\022\013\n\003str\030\006 \001(\t\022\020\n\010byte_str\030" +
      "\007 \001(\014\"\033\n\007Complex\022\020\n\010str_list\030\001 \003(\tB(\n\027ce" +
      "real.objects.protobufB\013SimpleOuterH\001"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_cereal_protobuf_Simple_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_cereal_protobuf_Simple_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cereal_protobuf_Simple_descriptor,
        new java.lang.String[] { "Dub", "Flt", "Int", "Long", "Boolean", "Str", "ByteStr", });
    internal_static_cereal_protobuf_Complex_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_cereal_protobuf_Complex_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_cereal_protobuf_Complex_descriptor,
        new java.lang.String[] { "StrList", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
